import { IChoice } from 'App/Modules/Question/Interfaces/ChoiceInterface'

export const LikertChoicesDefault: Array<IChoice.DTO.Edit> = [
  {
    sentence: 'NUNCA',
    label: '0',
    value: 0,
    order: 1,
  },
  {
    sentence: 'QUASE NUNCA',
    label: '1',
    value: 1,
    order: 2,
  },
  {
    sentence: 'ALGUMAS VEZES',
    label: '2',
    value: 2,
    order: 3,
  },
  {
    sentence: 'QUASE SEMPRE',
    label: '3',
    value: 3,
    order: 4,
  },
  {
    sentence: 'SEMPRE',
    label: '4',
    value: 4,
    order: 5,
  },
]

export const TimeChoicesDefault: Array<IChoice.DTO.Edit> = [
  {
    sentence: 'NUNCA',
    value: 1,
    order: 1,
  },
  {
    sentence: 'ANUALMENTE',
    value: 2,
    order: 2,
  },
  {
    sentence: 'MENSALMENTE',
    value: 3,
    order: 3,
  },
  {
    sentence: 'SEMANALMENTE',
    value: 4,
    order: 4,
  },
  {
    sentence: 'DIARIAMENTE',
    value: 5,
    order: 5,
  },
]

export const OpinionChoicesDefault: Array<IChoice.DTO.Edit> = [
  { sentence: 'DISCORDO TOTALMENTE', value: 1, order: 1 },
  { sentence: 'DISCORDO EM BOA PARTE', value: 2, order: 2 },
  { sentence: 'NÃO CONCORDO NEM DISCORDO', value: 3, order: 3 },
  { sentence: 'CONCORDO EM BOA PARTE', value: 4, order: 4 },
  { sentence: 'CONCORDO TOTALMENTE', value: 5, order: 5 },
]

export const BinaryChoicesDefault: Array<IChoice.DTO.Edit> = [
  {
    sentence: 'SIM',
    value: 1,
    order: 1,
  },
  {
    sentence: 'NÃO',
    value: 0,
    order: 2,
  },
]

export const MeasurableChoicesDefault: Array<IChoice.DTO.Edit> = [
  {
    sentence: 'Nada',
    value: 0,
    order: 1,
  },
  {
    sentence: 'Não muito',
    value: 1,
    order: 2,
  },
  {
    sentence: 'Um pouco',
    value: 2,
    order: 3,
  },
  {
    sentence: 'Bastante',
    value: 3,
    order: 4,
  },
  {
    sentence: 'Totalmente',
    value: 4,
    order: 5,
  },
]

export const NumberChoicesDefault: Array<IChoice.DTO.Edit> = [
  {
    sentence: '0',
    value: 0,
    order: 1,
  },
  {
    sentence: '1',
    value: 1,
    order: 2,
  },
  {
    sentence: '2',
    value: 2,
    order: 3,
  },
  {
    sentence: '3',
    value: 3,
    order: 4,
  },
]

export const MotivadoresChoicesDefault: Array<IChoice.DTO.Edit & { question: number }> = [
  {
    sentence: 'um salário compatível com as minhas necessidades básicas e as de minha família.',
    value: 0,
    order: 1,
    question: 1,
  },
  {
    sentence:
      'a oportunidade de testar a minha própria capacidade de ter acesso aos meus resultados.',
    value: 0,
    order: 2,
    question: 1,
  },
  {
    sentence:
      'me oferecer normas de trabalho claramente definidas, sólidas garantias de estabilidade e assegurar-me privilégios mais amplos de assistência médico-hospitalar.',
    value: 0,
    order: 3,
    question: 2,
  },
  {
    sentence:
      'me proporcionar autonomia para criar liberdade para experimentar e autoridade para inovar.',
    value: 0,
    order: 4,
    question: 2,
  },
  {
    sentence:
      'não valoriza as boas condições ambientais de trabalho que lhe são oferecidas (instalações físicas confortáveis, bem iluminadas, restaurante interno, etc).',
    value: 0,
    order: 5,
    question: 3,
  },
  {
    sentence: 'não me confere o devido respeito e consideração.',
    value: 0,
    order: 6,
    question: 3,
  },
  {
    sentence: 'recebo um salário compatível com minhas necessidades básicas e as de minha família.',
    value: 0,
    order: 7,
    question: 4,
  },
  {
    sentence:
      'mantenho um relacionamento cordial e harmonioso com meus colegas, meus superiores e meus subordinados, bem como a convicção de que sou bem aceito por eles.',
    value: 0,
    order: 8,
    question: 4,
  },
  {
    sentence:
      'me oferecer normas de trabalho claramente definidas, sólidas garantias de estabilidade e assegurar-me privilégios mais amplos de assistência médico-hospitalar.',
    value: 0,
    order: 9,
    question: 5,
  },
  {
    sentence: 'me conferir maior prestígio e poder.',
    value: 0,
    order: 10,
    question: 5,
  },
  {
    sentence:
      'me delegam responsabilidade que exige minha dedicação pessoal, e fico privado de compartilhar os meus problemas e as minhas idéias com meus companheiros.',
    value: 0,
    order: 11,
    question: 6,
  },
  {
    sentence: 'as minhas responsabilidades atuais deixarem de representar um desafio.',
    value: 0,
    order: 12,
    question: 6,
  },
  {
    sentence:
      'um supervisor imediato em quem eu possa confiar, condições de trabalho bem organizadas, e um ambiente de trabalho onde quase tudo já foi previsto e planejado.',
    value: 0,
    order: 13,
    question: 7,
  },
  {
    sentence: 'o reconhecimento que me conferem exclusivamente em função dos meus méritos.',
    value: 0,
    order: 14,
    question: 7,
  },
  {
    sentence:
      'me oferecer boas condições de trabalho: ambiente confortável, amplo e limpo, com boa iluminação e temperatura agradável, restaurante interno com comida saborosa.',
    value: 0,
    order: 15,
    question: 8,
  },
  {
    sentence:
      'me convidar para fazer parte de uma equipe de trabalho, que mantém excelentes relações entre os seus membros.',
    value: 0,
    order: 16,
    question: 8,
  },
  {
    sentence: 'não me confere o devido respeito e consideração.',
    value: 0,
    order: 17,
    question: 9,
  },
  {
    sentence: 'resiste a colaborar comigo na experimentação de novas idéias.',
    value: 0,
    order: 18,
    question: 9,
  },
  {
    sentence:
      'tenho um supervisor imediato em quem eu possa confiar, condições de trabalho bem organizadas, e um ambiente de trabalho onde quase tudo já foi previsto e planejado.',
    value: 0,
    order: 19,
    question: 10,
  },
  {
    sentence:
      'me proporcionam a oportunidade de testar a minha própria capacidade e tenho acesso aos meus resultados.',
    value: 0,
    order: 20,
    question: 10,
  },
  {
    sentence:
      'me oferecer boas condições de trabalho: ambiente confortável, amplo e limpo, com boa iluminação e temperatura agradável, restaurante interno com comida saborosa.',
    value: 0,
    order: 21,
    question: 11,
  },
  {
    sentence: 'me conferir maior prestígio e poder.',
    value: 0,
    order: 22,
    question: 11,
  },
  {
    sentence:
      'sou excessivamente solicitado no exercício de minhas atribuições a ponto de ter que sacrificar sistematicamente o meu horário de almoço ou de saída.',
    value: 0,
    order: 23,
    question: 12,
  },
  {
    sentence: 'as minhas responsabilidades atuais deixarem de representar um desafio.',
    value: 0,
    order: 24,
    question: 12,
  },
  {
    sentence: 'um salário compatível com as minhas necessidades básicas e as de minha família.',
    value: 0,
    order: 25,
    question: 13,
  },
  {
    sentence:
      'um supervisor imediato em quem eu possa confiar, condições de trabalho bem organizadas, e um ambiente de trabalho onde quase tudo já foi previsto e planejado.',
    value: 0,
    order: 26,
    question: 13,
  },
  {
    sentence:
      'um supervisor imediato em quem eu possa confiar, condições de trabalho bem organizadas, e um ambiente de trabalho onde quase tudo já foi previsto e planejado.',
    value: 0,
    order: 27,
    question: 14,
  },
  {
    sentence:
      'me convidar para fazer parte de uma equipe de trabalho, que mantém excelentes relações entre os seus membros.',
    value: 0,
    order: 28,
    question: 14,
  },
  {
    sentence: 'não pensa no dia de amanhã.',
    value: 0,
    order: 29,
    question: 15,
  },
  {
    sentence: 'é anti-social e confunde qualquer iniciativa de sociabilidade com "puxa-saquismo".',
    value: 0,
    order: 30,
    question: 15,
  },
  {
    sentence: 'me conferem reconhecimento em função dos meus méritos exclusivamente.',
    value: 0,
    order: 31,
    question: 16,
  },
  {
    sentence:
      'me proporcionam a oportunidade de testar a minha própria capacidade e tenho acesso aos meus resultados.',
    value: 0,
    order: 32,
    question: 16,
  },
  {
    sentence:
      'me oferecer boas condições de trabalho: ambiente confortável, amplo e limpo, com boa iluminação e temperatura agradável, restaurante interno com comida saborosa.',
    value: 0,
    order: 33,
    question: 17,
  },
  {
    sentence:
      'me oferecer normas de trabalho claramente definidas, sólidas garantias de estabilidade e assegurar-me privilégios mais amplos de assistência médico-hospitalar.',
    value: 0,
    order: 34,
    question: 17,
  },
  {
    sentence:
      'me delegam responsabilidade que exige minha dedicação pessoal, e fico privado de compartilhar os meus problemas e as minhas idéias com meus companheiros.',
    value: 0,
    order: 35,
    question: 18,
  },
  {
    sentence:
      'outro executivo, sem as qualificações que possuo, for promovido por mero favoritismo para o cargo que eu estou planejando assumir no futuro próximo.',
    value: 0,
    order: 36,
    question: 18,
  },
  {
    sentence:
      'o relacionamento cordial e harmonioso com os meus colegas, meus superiores e meus subordinados, bem como a convicção de que sou bem aceito por eles.',
    value: 0,
    order: 37,
    question: 19,
  },
  {
    sentence: 'o reconhecimento que me conferem exclusivamente em função dos meus méritos.',
    value: 0,
    order: 38,
    question: 19,
  },
  {
    sentence: 'me oferecer um cargo que confira maior prestígio e poder.',
    value: 0,
    order: 39,
    question: 20,
  },
  {
    sentence:
      'me proporcionar autonomia para criar liberdade para experimentar e autoridade para inovar.',
    value: 0,
    order: 40,
    question: 20,
  },
  {
    sentence:
      'não valoriza as boas condições ambientais de trabalho que lhe são oferecidas (instalações físicas confortáveis, bem iluminadas, restaurante interno, etc).',
    value: 0,
    order: 41,
    question: 21,
  },
  {
    sentence: 'é anti-social e confunde qualquer iniciativa de sociabilidade com "puxa-saquismo".',
    value: 0,
    order: 42,
    question: 21,
  },
  {
    sentence:
      'mantenho um relacionamento cordial e harmonioso com meus colegas, meus superiores e meus subordinados, bem como a convicção de que sou bem aceito por eles.',
    value: 0,
    order: 43,
    question: 22,
  },
  {
    sentence:
      'me proporcionam a oportunidade de testar a minha própria capacidade e tenho acesso aos meus resultados.',
    value: 0,
    order: 44,
    question: 22,
  },
  {
    sentence:
      'me oferecer boas condições de trabalho: ambiente confortável, amplo e limpo, com boa iluminação e temperatura agradável, restaurante interno com comida saborosa.',
    value: 0,
    order: 45,
    question: 23,
  },
  {
    sentence:
      'me proporcionar autonomia para criar liberdade para experimentar e autoridade para inovar.',
    value: 0,
    order: 46,
    question: 23,
  },
  {
    sentence:
      'perco a confiança no meu chefe, desconfio da estabilidade do meu cargo, temo pela sobrevivência da minha organização.',
    value: 0,
    order: 47,
    question: 24,
  },
  {
    sentence:
      'outro executivo, sem as qualificações que possuo, for promovido por mero favoritismo para o cargo que eu estou planejando assumir no futuro próximo.',
    value: 0,
    order: 48,
    question: 24,
  },
  {
    sentence: 'um salário compatível com as minhas necessidades básicas e as de minha família.',
    value: 0,
    order: 49,
    question: 25,
  },
  {
    sentence: 'o reconhecimento que me conferem exclusivamente em função dos meus méritos.',
    value: 0,
    order: 50,
    question: 25,
  },
  {
    sentence: 'me oferecer um cargo que confira maior prestígio e poder.',
    value: 0,
    order: 51,
    question: 26,
  },
  {
    sentence:
      'me convidar para fazer parte de uma equipe de trabalho, que mantém excelentes relações entre os seus membros.',
    value: 0,
    order: 52,
    question: 26,
  },
  {
    sentence: 'não pensa no dia de amanhã.',
    value: 0,
    order: 53,
    question: 27,
  },
  {
    sentence: 'resiste a colaborar comigo na experimentação de novas idéias.',
    value: 0,
    order: 54,
    question: 27,
  },
  {
    sentence:
      'tenho um supervisor imediato em quem eu possa confiar, condições de trabalho bem organizadas, e um ambiente de trabalho onde quase tudo já foi previsto e planejado.',
    value: 0,
    order: 55,
    question: 28,
  },
  {
    sentence:
      'mantenho um relacionamento cordial e harmonioso com meus colegas, meus superiores e meus subordinados, bem como a convicção de que sou bem aceito por eles.',
    value: 0,
    order: 56,
    question: 28,
  },
  {
    sentence: 'trabalho que mantém excelentes relações entre os seus membros.',
    value: 0,
    order: 57,
    question: 29,
  },
  {
    sentence:
      'me proporcionar autonomia para criar liberdade para experimentar e autoridade para inovar.',
    value: 0,
    order: 58,
    question: 29,
  },
  {
    sentence:
      'sou excessivamente solicitado no exercício de minhas atribuições a ponto de ter que sacrificar sistematicamente o meu horário de almoço ou de saída.',
    value: 0,
    order: 59,
    question: 30,
  },
  {
    sentence:
      'perco a confiança no meu chefe, desconfio da estabilidade do meu cargo, temo pela sobrevivência da minha organização.',
    value: 0,
    order: 60,
    question: 30,
  },
]

export const AssertividadeChoicesDefault: Array<IChoice.DTO.Edit & { question: number }> = [
  {
    sentence: 'Afasta-se o mais rápido que puder, deixando que os dois resolvam.',
    value: 0,
    order: 1,
    question: 1,
  },
  {
    sentence: 'Mostra-se tranquilo (embora não esteja) e se afasta com calma.',
    value: 0,
    order: 2,
    question: 1,
  },
  {
    sentence: 'Revela a eles os seus temores e ajuda a resolver o problema.',
    value: 0,
    order: 3,
    question: 1,
  },
  {
    sentence: 'Evita rir muito para não aparecer demais.',
    value: 0,
    order: 4,
    question: 2,
  },
  {
    sentence: 'Ri muito na proporção em que a coisa é engraçada.',
    value: 0,
    order: 5,
    question: 2,
  },
  {
    sentence: 'Dá grandes gargalhadas, não se importando com o ambiente.',
    value: 0,
    order: 6,
    question: 2,
  },
  {
    sentence: 'Cala-se para evitar atrito maior.',
    value: 0,
    order: 7,
    question: 3,
  },
  {
    sentence: 'Expressa seu descontentamento diretamente.',
    value: 0,
    order: 8,
    question: 3,
  },
  {
    sentence: 'Cria um caso à altura da injustiça.',
    value: 0,
    order: 9,
    question: 3,
  },
  {
    sentence: 'Muda de fisionomia e diz ao seu filho: Impressão sua, está tudo bem!',
    value: 0,
    order: 10,
    question: 4,
  },
  {
    sentence: 'Diz apenas: Nada, meu filho. Estou pensando.',
    value: 0,
    order: 11,
    question: 4,
  },
  {
    sentence: 'Diz: É, meu filho, estou triste hoje. Alguns problemas.',
    value: 0,
    order: 12,
    question: 4,
  },
  {
    sentence: 'Ri com eles. Como se tivessem razão.',
    value: 0,
    order: 13,
    question: 5,
  },
  {
    sentence: 'Fica calado(a) evitando criar discussões.',
    value: 0,
    order: 14,
    question: 5,
  },
  {
    sentence: 'Discorda abertamente dizendo que gostou muito.',
    value: 0,
    order: 15,
    question: 5,
  },
  {
    sentence: 'Por educação convida-o a entrar e escuta a sua argumentação.',
    value: 0,
    order: 16,
    question: 6,
  },
  {
    sentence: 'Diz-lhe diretamente que não quer ouvi-lo.',
    value: 0,
    order: 17,
    question: 6,
  },
  {
    sentence: 'Pede-lhe para passar noutra hora e fica livre dele, sem atrito.',
    value: 0,
    order: 18,
    question: 6,
  },
  {
    sentence: 'Fica com a roupa defeituosa, para evitar maiores problemas com o vendedor.',
    value: 0,
    order: 19,
    question: 7,
  },
  {
    sentence: 'Procura logo a loja e argumenta, seriamente, com o vendedor para trocar.',
    value: 0,
    order: 20,
    question: 7,
  },
  {
    sentence: 'Procura logo a loja e argumenta, seriamente, com o vendedor para trocar.',
    value: 0,
    order: 21,
    question: 7,
  },
  {
    sentence: 'Procura logo a loja e argumenta, seriamente, com o vendedor para trocar.',
    value: 0,
    order: 22,
    question: 8,
  },
  {
    sentence: 'Procura mostrar a ele que, acima de tudo, ele é corajoso e forte.',
    value: 0,
    order: 23,
    question: 8,
  },
  {
    sentence: 'Diz a ele que, na idade dele, você também teria medo daquela situação.',
    value: 0,
    order: 24,
    question: 8,
  },
  {
    sentence: 'Muitas vezes.',
    value: 0,
    order: 25,
    question: 9,
  },
  {
    sentence: 'Sempre.',
    value: 0,
    order: 26,
    question: 9,
  },
  {
    sentence: 'Nunca.',
    value: 0,
    order: 27,
    question: 9,
  },
  {
    sentence: 'Corta relações com ele e passa a evitá-lo.',
    value: 0,
    order: 28,
    question: 10,
  },
  {
    sentence: 'Procura-o e manifesta sua raiva e decepção.',
    value: 0,
    order: 29,
    question: 10,
  },
  {
    sentence: 'Xinga e esbraveja para que ele veja o que fez.',
    value: 0,
    order: 30,
    question: 10,
  },
  {
    sentence: 'Recolhe-se na cadeira e fecha os olhos para afastar seu sentimento.',
    value: 0,
    order: 31,
    question: 11,
  },
  {
    sentence: 'Contém seu choro, de modo a sentir apenas um aperto na garganta.',
    value: 0,
    order: 32,
    question: 11,
  },
  {
    sentence: 'Chora, levado pelo que sente.',
    value: 0,
    order: 33,
    question: 11,
  },
  {
    sentence: 'Abre mão da música, embora a contra gosto, e empresta o aparelho.',
    value: 0,
    order: 34,
    question: 12,
  },
  {
    sentence: 'Arranja a desculpa de que o aparelho está estragado.',
    value: 0,
    order: 35,
    question: 12,
  },
  {
    sentence: 'Diz à pessoa que você planeja usar o aparelho naquela noite.',
    value: 0,
    order: 36,
    question: 12,
  },
  {
    sentence: 'Nada lhe fala, espera simplesmente.',
    value: 0,
    order: 37,
    question: 13,
  },
  {
    sentence: 'Cobra dele na primeira ocasião oportuna.',
    value: 0,
    order: 38,
    question: 13,
  },
  {
    sentence: 'Nada lhe fala, mas, perde a confiança total nele.',
    value: 0,
    order: 39,
    question: 13,
  },
  {
    sentence: 'Evita ir para não cometer gafes.',
    value: 0,
    order: 40,
    question: 14,
  },
  {
    sentence: 'Vai , levando no bolso um manual de boas maneiras.',
    value: 0,
    order: 41,
    question: 14,
  },
  {
    sentence: 'Vai, sem se preocupar com gafes que possa dar.',
    value: 0,
    order: 42,
    question: 14,
  },
  {
    sentence: 'Certa.',
    value: 0,
    order: 43,
    question: 15,
  },
  {
    sentence: 'Certa, na maioria dos casos.',
    value: 0,
    order: 44,
    question: 15,
  },
  {
    sentence: 'Errada.',
    value: 0,
    order: 45,
    question: 15,
  },
  {
    sentence: 'Cala-se para não criar problemas maiores.',
    value: 0,
    order: 46,
    question: 16,
  },
  {
    sentence: 'Dirige-se ao "furador" e manifesta seu desagrado adequadamente.',
    value: 0,
    order: 47,
    question: 16,
  },
  {
    sentence: 'Grita e obriga-o a se retirar de onde entrou, sem direito.',
    value: 0,
    order: 48,
    question: 16,
  },
  {
    sentence: 'Ocupar-se para afastar o que sente.',
    value: 0,
    order: 49,
    question: 17,
  },
  {
    sentence: 'Bebe ou fazer algo para alegrar-se.',
    value: 0,
    order: 50,
    question: 17,
  },
  {
    sentence: 'Deixar que a tristeza passe por si mesma.',
    value: 0,
    order: 51,
    question: 17,
  },
  {
    sentence: 'Nunca lhe disse desta forma.',
    value: 0,
    order: 52,
    question: 18,
  },
  {
    sentence: 'Há mais de um ano.',
    value: 0,
    order: 53,
    question: 18,
  },
  {
    sentence: 'Há menos de um ano.',
    value: 0,
    order: 54,
    question: 18,
  },
  {
    sentence: 'Aceita por educação.',
    value: 0,
    order: 55,
    question: 19,
  },
  {
    sentence: 'Diz que gosta, mas não quer.',
    value: 0,
    order: 56,
    question: 19,
  },
  {
    sentence: 'Diz que não gosta.',
    value: 0,
    order: 57,
    question: 19,
  },
  {
    sentence: 'Fica no fundo, de pé, para evitar incomodar os outros.',
    value: 0,
    order: 58,
    question: 20,
  },
  {
    sentence: 'Pede licença a cada um e se dirige para as primeiras filas.',
    value: 0,
    order: 59,
    question: 20,
  },
  {
    sentence: 'Força a passagem, pois os que estão de pé é que estão errados.',
    value: 0,
    order: 60,
    question: 20,
  },
  {
    sentence: 'Sorri alegre. Não permite que ele veja que você está com medo.',
    value: 0,
    order: 61,
    question: 21,
  },
  {
    sentence: 'Diz a ele que estava com medo e se aliviou quando o identificou.',
    value: 0,
    order: 62,
    question: 21,
  },
  {
    sentence:
      'Dá-lhe uma bronca pelo susto que ele lhe passou, vindo tão diretamente em sua direção.',
    value: 0,
    order: 63,
    question: 21,
  },
  {
    sentence: 'Certa.',
    value: 0,
    order: 64,
    question: 22,
  },
  {
    sentence: 'Certa na maioria dos casos.',
    value: 0,
    order: 65,
    question: 22,
  },
  {
    sentence: 'Errada.',
    value: 0,
    order: 66,
    question: 22,
  },
  {
    sentence: 'Procura evitá-lo, custe o que custar.',
    value: 0,
    order: 67,
    question: 23,
  },
  {
    sentence: 'Dirige-se a ele e revela seu aborrecimento.',
    value: 0,
    order: 68,
    question: 23,
  },
  {
    sentence: 'Corta relações com ele de vez.',
    value: 0,
    order: 69,
    question: 23,
  },
  {
    sentence: 'Perde toda a capacidade de agir, sente-se sem forças.',
    value: 0,
    order: 70,
    question: 24,
  },
  {
    sentence: 'Age, apesar de triste e sem esconder o que sente.',
    value: 0,
    order: 71,
    question: 24,
  },
  {
    sentence: 'Não se entrega, reage, sorri e enfrenta tudo.',
    value: 0,
    order: 72,
    question: 24,
  },
  {
    sentence: 'Errada.',
    value: 0,
    order: 73,
    question: 25,
  },
  {
    sentence: 'Correta para quase todos os casos.',
    value: 0,
    order: 74,
    question: 25,
  },
  {
    sentence: 'Correta.',
    value: 0,
    order: 75,
    question: 25,
  },
  {
    sentence: 'Faz o que o chefe lhe pede.',
    value: 0,
    order: 76,
    question: 26,
  },
  {
    sentence: 'Diz diretamente ao chefe que não pode executar o que lhe pede.',
    value: 0,
    order: 77,
    question: 26,
  },
  {
    sentence: 'Mostra ao chefe que ele será responsável pelo atraso da rotina.',
    value: 0,
    order: 78,
    question: 26,
  },
  {
    sentence: 'Aceita sem discutir embora isso lhe desagrade.',
    value: 0,
    order: 79,
    question: 27,
  },
  {
    sentence:
      'Recusa-se calmamente a receber o troco incompleto e pede solução que não lhe prejudique.',
    value: 0,
    order: 80,
    question: 27,
  },
  {
    sentence: 'Aceita o troco incompleto e lhe diz cara a cara que não voltará a comprar ali.',
    value: 0,
    order: 81,
    question: 27,
  },
  {
    sentence: 'Eu te amo.',
    value: 0,
    order: 82,
    question: 28,
  },
  {
    sentence: 'Abraços e até breve.',
    value: 0,
    order: 83,
    question: 28,
  },
  {
    sentence: 'Muitas saudades.',
    value: 0,
    order: 84,
    question: 28,
  },
]

export const GerencialChoicesDefault: Array<IChoice.DTO.Edit & { question: number }> = [
  {
    sentence: 'Ao decidir, uso principalmente a intuição.',
    value: 0,
    order: 1,
    question: 1,
  },
  {
    sentence: 'Depois de decidir, fico ansioso com a decisão tomada.',
    value: 0,
    order: 2,
    question: 1,
  },
  {
    sentence: 'Quando tomo decisões, preocupo-me em não ferir ninguém.',
    value: 0,
    order: 3,
    question: 1,
  },
  {
    sentence: 'Só decido depois de analisar os fatos e de me assegurar quanto aos resultados.',
    value: 0,
    order: 4,
    question: 1,
  },
  {
    sentence: 'Só decido quando pressionado.',
    value: 0,
    order: 5,
    question: 1,
  },
  {
    sentence: 'Normalmente decido sem fazer consultas.',
    value: 0,
    order: 6,
    question: 1,
  },
  {
    sentence: 'Geralmente, decido à revelia de meus subordinados.',
    value: 0,
    order: 7,
    question: 1,
  },
  {
    sentence: 'Quando decido, não cogito de meus preconceitos.',
    value: 0,
    order: 8,
    question: 1,
  },
  {
    sentence: 'Antes de decidir, procuro avaliar os efeitos negativos da decisão sobre meus atos.',
    value: 0,
    order: 9,
    question: 1,
  },
  {
    sentence: 'Decido de acordo com minha disposição no momento.',
    value: 0,
    order: 10,
    question: 1,
  },
  {
    sentence: 'Fico com raiva quando me dizem o que fazer.',
    value: 0,
    order: 11,
    question: 1,
  },
  {
    sentence: 'Quero minhas decisões cumpridas depressa e sem interferência.',
    value: 0,
    order: 12,
    question: 1,
  },
  {
    sentence: 'Recuso-me aceitar a interferência de subordinados na programação do trabalho.',
    value: 0,
    order: 13,
    question: 2,
  },
  {
    sentence: 'Quando localizo um ponto fraco na programação, procuro saná-lo dentro do possível.',
    value: 0,
    order: 14,
    question: 2,
  },
  {
    sentence: 'Para mim, fazer programação de trabalho é dispensável.',
    value: 0,
    order: 15,
    question: 2,
  },
  {
    sentence: 'Sinto-me inseguro sem uma programação a seguir.',
    value: 0,
    order: 16,
    question: 2,
  },
  {
    sentence: 'Sigo a programação com base nas circunstâncias.',
    value: 0,
    order: 17,
    question: 2,
  },
  {
    sentence: 'Procuro programar com flexibilidade para não prejudicar meus subordinados.',
    value: 0,
    order: 18,
    question: 2,
  },
  {
    sentence: 'Fazer programações me incomoda.',
    value: 0,
    order: 19,
    question: 2,
  },
  {
    sentence:
      'Procuro fazer programações bem definidas e claras para evitar desvios, reclamações e perdas.',
    value: 0,
    order: 20,
    question: 2,
  },
  {
    sentence: 'Acho mais importante improvisar do que ficar preso a programações.',
    value: 0,
    order: 21,
    question: 2,
  },
  {
    sentence: 'Ao programar as atividades, sempre considero os interesses pessoais envolvidos.',
    value: 0,
    order: 22,
    question: 2,
  },
  {
    sentence: 'Fico revoltado quando tenho que seguir o que outros programam.',
    value: 0,
    order: 23,
    question: 2,
  },
  {
    sentence: 'Quando não há programação a seguir, prefiro ficar aguardando ordens.',
    value: 0,
    order: 24,
    question: 2,
  },
  {
    sentence: 'Fico revoltado por ter que cumprir horários.',
    value: 0,
    order: 25,
    question: 3,
  },
  {
    sentence:
      'Sinto-me mal quando tenho de exigir cumprimento das obrigações de meus subordinados.',
    value: 0,
    order: 26,
    question: 3,
  },
  {
    sentence: 'Quando dou ordens, quero providências imediatas.',
    value: 0,
    order: 27,
    question: 3,
  },
  {
    sentence: 'Executo melhor as atividades que me dão prazer.',
    value: 0,
    order: 28,
    question: 3,
  },
  {
    sentence: 'Tenho vontade de fazer o contrário do que me ordenam.',
    value: 0,
    order: 29,
    question: 3,
  },
  {
    sentence: 'Procuro conciliar a exigência do serviço com as características dos funcionários.',
    value: 0,
    order: 30,
    question: 3,
  },
  {
    sentence: 'Faço o máximo para não receber reclamações.',
    value: 0,
    order: 31,
    question: 3,
  },
  {
    sentence: 'Preocupo-me com o desenvolvimento constante de meus subordinados.',
    value: 0,
    order: 32,
    question: 3,
  },
  {
    sentence: 'Faço mais o que me agrada do que aquilo que é forçoso.',
    value: 0,
    order: 33,
    question: 3,
  },
  {
    sentence: 'Faço mais o que me agrada do que aquilo que é forçoso.',
    value: 0,
    order: 34,
    question: 3,
  },
  {
    sentence: 'Procuro conhecer meus subordinados e o clima que os cerca.',
    value: 0,
    order: 35,
    question: 3,
  },
  {
    sentence: 'Exijo o máximo dos que trabalham comigo.',
    value: 0,
    order: 36,
    question: 3,
  },
  {
    sentence: 'Exerço controle constante e "de perto" sobre meus subordinados.',
    value: 0,
    order: 37,
    question: 4,
  },
  {
    sentence: 'Ao exercer controle, confio mais na intuição.',
    value: 0,
    order: 38,
    question: 4,
  },
  {
    sentence: 'Detesto que me controlem.',
    value: 0,
    order: 39,
    question: 4,
  },
  {
    sentence: 'Sem o controle sob o que faço, fico completamente "no ar".',
    value: 0,
    order: 40,
    question: 4,
  },
  {
    sentence: 'Em matéria de controle, confio bastante no autocontrole.',
    value: 0,
    order: 41,
    question: 4,
  },
  {
    sentence: 'Controlo para evitar que as pessoas errem, e com isso sejam prejudicadas.',
    value: 0,
    order: 42,
    question: 4,
  },
  {
    sentence: 'Controlo meus subordinados para que eles se sintam seguros.',
    value: 0,
    order: 43,
    question: 4,
  },
  {
    sentence:
      'Exerço o controle das atividades conforme o desempenho e as características de cada subordinado.',
    value: 0,
    order: 44,
    question: 4,
  },
  {
    sentence: 'Tenho vontade de fazer o contrário do que me mandam.',
    value: 0,
    order: 45,
    question: 4,
  },
  {
    sentence: 'É preciso controlar as pessoas para que elas não cometam erros.',
    value: 0,
    order: 46,
    question: 4,
  },
  {
    sentence: 'Aprecio que controlem minhas atividades, o que me dá mais segurança.',
    value: 0,
    order: 47,
    question: 4,
  },
  {
    sentence:
      'Reduzo o controle na medida em que o subordinado se torna mais autônomo em suas tarefas.',
    value: 0,
    order: 48,
    question: 4,
  },
  {
    sentence: 'Só ouso sugerir modificações quando me solicitam.',
    value: 0,
    order: 49,
    question: 5,
  },
  {
    sentence: 'Desagrada-me adotar as mudanças determinadas por meus superiores.',
    value: 0,
    order: 50,
    question: 5,
  },
  {
    sentence: 'Resisto a pessoas inovadoras; desconfio das suas intenções.',
    value: 0,
    order: 51,
    question: 5,
  },
  {
    sentence:
      'Pressinto quando surge a necessidade de iniciar um processo de mudança na organização.',
    value: 0,
    order: 52,
    question: 5,
  },
  {
    sentence:
      'Quando participo do processo de mudança, preocupo-me em que ele não prejudique ninguém.',
    value: 0,
    order: 53,
    question: 5,
  },
  {
    sentence: 'Pouco me importa mudar ou não, desde que acatando as ordens superiores.',
    value: 0,
    order: 54,
    question: 5,
  },
  {
    sentence: 'Deixo a critério de cada um a necessidade de mudanças organizacionais.',
    value: 0,
    order: 55,
    question: 5,
  },
  {
    sentence:
      'Sempre que tenho uma ideia, analiso sua aplicabilidade à organização antes de sugeri-la ou executá-la.',
    value: 0,
    order: 56,
    question: 5,
  },
  {
    sentence: 'Tenho vontade de mudar tudo, só para quebrar a tradição.',
    value: 0,
    order: 57,
    question: 5,
  },
  {
    sentence: 'Penso que enquanto as pessoas estiverem satisfeitas, não há o que mudar.',
    value: 0,
    order: 58,
    question: 5,
  },
  {
    sentence:
      'Durante os processos de mudança, procuro aumentar as oportunidades de participação dos subordinados nas decisões.',
    value: 0,
    order: 59,
    question: 5,
  },
  {
    sentence:
      'Quando conduzo um processo de mudança, não me importo com os problemas pessoais de meus subordinados.',
    value: 0,
    order: 60,
    question: 5,
  },
]

export const CerebralChoicesDefault: Array<IChoice.DTO.Edit & { question: number }> = [
  {
    sentence: 'Trabalhar sozinho',
    value: 0,
    order: 1,
    question: 1,
  },
  {
    sentence: 'Expressar minhas idéias',
    value: 0,
    order: 2,
    question: 1,
  },
  {
    sentence: 'Estar no controle da situação',
    value: 0,
    order: 3,
    question: 1,
  },
  {
    sentence: 'Provocar mudanças',
    value: 0,
    order: 4,
    question: 1,
  },
  {
    sentence: 'Ouvir e falar',
    value: 0,
    order: 5,
    question: 1,
  },
  {
    sentence: 'Criar ou usar recursos visuais',
    value: 0,
    order: 6,
    question: 1,
  },
  {
    sentence: 'Prestar atenção aos detalhes',
    value: 0,
    order: 7,
    question: 1,
  },
  {
    sentence: 'Aspectos técnicos',
    value: 0,
    order: 8,
    question: 1,
  },
  {
    sentence: 'Trabalhar com pessoas',
    value: 0,
    order: 9,
    question: 1,
  },
  {
    sentence: 'Usar números, estatísticas',
    value: 0,
    order: 10,
    question: 1,
  },
  {
    sentence: 'Oportunidades para fazer experiências',
    value: 0,
    order: 11,
    question: 1,
  },
  {
    sentence: 'Planejar',
    value: 0,
    order: 12,
    question: 1,
  },
  {
    sentence: 'Trabalhar com comunicação',
    value: 0,
    order: 13,
    question: 1,
  },
  {
    sentence: 'Fazer algo funcionar',
    value: 0,
    order: 14,
    question: 1,
  },
  {
    sentence: 'Arriscar-se',
    value: 0,
    order: 15,
    question: 1,
  },
  {
    sentence: 'Analisar dados',
    value: 0,
    order: 16,
    question: 1,
  },
  {
    sentence: 'Lidar com o futuro',
    value: 0,
    order: 17,
    question: 1,
  },
  {
    sentence: 'Produzir e organizar',
    value: 0,
    order: 18,
    question: 1,
  },
  {
    sentence: 'Fazer parte de uma equipe',
    value: 0,
    order: 19,
    question: 1,
  },
  {
    sentence: 'Fazer as coisas sempre no prazo previsto',
    value: 0,
    order: 20,
    question: 1,
  },
  {
    sentence: 'Avaliar e testar teorias',
    value: 0,
    order: 21,
    question: 2,
  },
  {
    sentence: 'Obter e quantificar fatos',
    value: 0,
    order: 22,
    question: 2,
  },
  {
    sentence: 'Ouvir e compartilhar idéias',
    value: 0,
    order: 23,
    question: 2,
  },
  {
    sentence: 'Usar minha imaginação',
    value: 0,
    order: 24,
    question: 2,
  },
  {
    sentence: 'Aplicar análise e lógica',
    value: 0,
    order: 25,
    question: 2,
  },
  {
    sentence: 'Ambiente bem informal',
    value: 0,
    order: 26,
    question: 2,
  },
  {
    sentence: 'Verificar meu entendimento',
    value: 0,
    order: 27,
    question: 2,
  },
  {
    sentence: 'Fazer experiências práticas',
    value: 0,
    order: 28,
    question: 2,
  },
  {
    sentence: 'Pensar sobre as idéias',
    value: 0,
    order: 29,
    question: 2,
  },
  {
    sentence: 'Confiar nas intuições',
    value: 0,
    order: 30,
    question: 2,
  },
  {
    sentence: 'Receber informações passo a passo',
    value: 0,
    order: 31,
    question: 2,
  },
  {
    sentence: 'Tomar iniciativas',
    value: 0,
    order: 32,
    question: 2,
  },
  {
    sentence: 'Elaborar teorias',
    value: 0,
    order: 33,
    question: 2,
  },
  {
    sentence: 'Envolvimento emocional',
    value: 0,
    order: 34,
    question: 2,
  },
  {
    sentence: 'Trabalhar em grupo',
    value: 0,
    order: 35,
    question: 2,
  },
  {
    sentence: 'Orientacões claras',
    value: 0,
    order: 36,
    question: 2,
  },
  {
    sentence: 'Fazer descobertas',
    value: 0,
    order: 37,
    question: 2,
  },
  {
    sentence: 'Criticar',
    value: 0,
    order: 38,
    question: 2,
  },
  {
    sentence: 'Perceber logo o quadro geral (o objetivo final)',
    value: 0,
    order: 39,
    question: 2,
  },
  {
    sentence: 'Adquirir habilidades pela prática',
    value: 0,
    order: 40,
    question: 2,
  },
  {
    sentence: 'Materiais visuais',
    value: 0,
    order: 41,
    question: 3,
  },
  {
    sentence: 'Demonstrações',
    value: 0,
    order: 42,
    question: 3,
  },
  {
    sentence: 'Debates estruturados pelo instrutor',
    value: 0,
    order: 43,
    question: 3,
  },
  {
    sentence: 'Palestras formais',
    value: 0,
    order: 44,
    question: 3,
  },
  {
    sentence: 'Experiências',
    value: 0,
    order: 45,
    question: 3,
  },
  {
    sentence: 'Utilizando histórias e músicas',
    value: 0,
    order: 46,
    question: 3,
  },
  {
    sentence: 'Exercícios que usam a intuição',
    value: 0,
    order: 47,
    question: 3,
  },
  {
    sentence: 'Debate em grupo',
    value: 0,
    order: 48,
    question: 3,
  },
  {
    sentence: 'Exercícios de análise',
    value: 0,
    order: 49,
    question: 3,
  },
  {
    sentence: 'Atividades sequenciais bem planejadas',
    value: 0,
    order: 50,
    question: 3,
  },
  {
    sentence: 'Analisando números, dados e fatos',
    value: 0,
    order: 51,
    question: 3,
  },
  {
    sentence: 'Exemplos com metáforas',
    value: 0,
    order: 52,
    question: 3,
  },
  {
    sentence: 'Atividades passo a passo de reforço do conteúdo',
    value: 0,
    order: 53,
    question: 3,
  },
  {
    sentence: 'Leitura de livros-textos',
    value: 0,
    order: 54,
    question: 3,
  },
  {
    sentence: 'Discussões de casos voltados para pessoas',
    value: 0,
    order: 55,
    question: 3,
  },
  {
    sentence: 'Discussões de casos voltados para os números e fatos',
    value: 0,
    order: 56,
    question: 3,
  },
  {
    sentence: 'Métodos tradicionais comprovados',
    value: 0,
    order: 57,
    question: 3,
  },
  {
    sentence: 'Agenda bem flexível',
    value: 0,
    order: 58,
    question: 3,
  },
  {
    sentence: 'Agenda estruturada com antecedência',
    value: 0,
    order: 59,
    question: 3,
  },
  {
    sentence: 'Trabalhos bem estruturados',
    value: 0,
    order: 60,
    question: 3,
  },
  {
    sentence: 'O quê?',
    value: 0,
    order: 61,
    question: 4,
  },
  {
    sentence: 'Como?',
    value: 0,
    order: 62,
    question: 4,
  },
  {
    sentence: 'Por quê?',
    value: 0,
    order: 63,
    question: 4,
  },
  {
    sentence: 'Quem?',
    value: 0,
    order: 64,
    question: 4,
  },
  {
    sentence: 'Descobrir',
    value: 0,
    order: 65,
    question: 5,
  },
  {
    sentence: 'Quantificar',
    value: 0,
    order: 66,
    question: 5,
  },
  {
    sentence: 'Envolver',
    value: 0,
    order: 67,
    question: 5,
  },
  {
    sentence: 'Organizar',
    value: 0,
    order: 68,
    question: 5,
  },
  {
    sentence: 'Conceituar',
    value: 0,
    order: 69,
    question: 5,
  },
  {
    sentence: 'Analisar dados',
    value: 0,
    order: 70,
    question: 5,
  },
  {
    sentence: 'Sentir',
    value: 0,
    order: 71,
    question: 5,
  },
  {
    sentence: 'Praticar',
    value: 0,
    order: 72,
    question: 5,
  },
  {
    sentence: 'Teorizar',
    value: 0,
    order: 73,
    question: 5,
  },
  {
    sentence: 'Sintetizar',
    value: 0,
    order: 74,
    question: 5,
  },
  {
    sentence: 'Avaliar e testar teorias',
    value: 0,
    order: 75,
    question: 5,
  },
  {
    sentence: 'Interiorizar',
    value: 0,
    order: 76,
    question: 5,
  },
  {
    sentence: 'Processar',
    value: 0,
    order: 77,
    question: 5,
  },
  {
    sentence: 'Ordenar',
    value: 0,
    order: 78,
    question: 5,
  },
  {
    sentence: 'Ordenar',
    value: 0,
    order: 79,
    question: 5,
  },
  {
    sentence: 'Compartilhar',
    value: 0,
    order: 80,
    question: 5,
  },
  {
    sentence: 'Compra com base na recomendação de amigos',
    value: 0,
    order: 81,
    question: 6,
  },
  {
    sentence: 'Se preocupa com o consumo de combustível',
    value: 0,
    order: 82,
    question: 6,
  },
  {
    sentence: 'Se preocupa com as formas , a cor e a tecnologia',
    value: 0,
    order: 83,
    question: 6,
  },
  {
    sentence: 'Verifica equipamento de segurança e durabilidade',
    value: 0,
    order: 84,
    question: 6,
  },
  {
    sentence: 'Dá importância à sensação de "conforto" do veículo',
    value: 0,
    order: 85,
    question: 6,
  },
  {
    sentence: 'Faz comparações com outros veículos',
    value: 0,
    order: 86,
    question: 6,
  },
  {
    sentence: 'Verifica o tamanho do porta-malas',
    value: 0,
    order: 87,
    question: 6,
  },
  {
    sentence: 'Verifica se encaixa no seu sonho de vida',
    value: 0,
    order: 88,
    question: 6,
  },
  {
    sentence: 'Pesquisa e planeja antecipadamente como vai utilizá-lo',
    value: 0,
    order: 89,
    question: 6,
  },
  {
    sentence: 'Se preocupa com o custo e o valor de troca',
    value: 0,
    order: 90,
    question: 6,
  },
  {
    sentence: 'Quer "amar" o carro',
    value: 0,
    order: 91,
    question: 6,
  },
  {
    sentence: 'Prefere carros lançados recentemente, novidades',
    value: 0,
    order: 92,
    question: 6,
  },
  {
    sentence: 'Se preocupa com os requisitos técnicos',
    value: 0,
    order: 93,
    question: 6,
  },
  {
    sentence: 'Verifica a facilidade de manutenção',
    value: 0,
    order: 94,
    question: 6,
  },
  {
    sentence: 'Gosta de experimentar um novo modelo ou fabricante',
    value: 0,
    order: 95,
    question: 6,
  },
  {
    sentence: 'Se preocupa com o nome do fabricante',
    value: 0,
    order: 96,
    question: 6,
  },
  {
    sentence: 'Dá importância à opinião das pessoas',
    value: 0,
    order: 97,
    question: 6,
  },
  {
    sentence: 'Quer ver dados e estatísticas sobre o desempenho',
    value: 0,
    order: 98,
    question: 6,
  },
  {
    sentence: 'Se preocupa com a qualidade do atendimento do revendedor',
    value: 0,
    order: 99,
    question: 6,
  },
  {
    sentence: 'Analisa como o carro vai ser útil no seu dia-a-dia',
    value: 0,
    order: 100,
    question: 6,
  },
  {
    sentence: 'Gosto de organizar',
    value: 0,
    order: 101,
    question: 7,
  },
  {
    sentence: 'Gosto de compartilhar',
    value: 0,
    order: 102,
    question: 7,
  },
  {
    sentence: 'Gosto de analisar',
    value: 0,
    order: 103,
    question: 7,
  },
  {
    sentence: 'Gosto de descobrir',
    value: 0,
    order: 104,
    question: 7,
  },
  {
    sentence: 'Organizado',
    value: 0,
    order: 105,
    question: 8,
  },
  {
    sentence: 'Analítico',
    value: 0,
    order: 106,
    question: 8,
  },
  {
    sentence: 'Emocional',
    value: 0,
    order: 107,
    question: 8,
  },
  {
    sentence: 'Experimental',
    value: 0,
    order: 108,
    question: 8,
  },
  {
    sentence: 'Lógico',
    value: 0,
    order: 109,
    question: 8,
  },
  {
    sentence: 'Conceitual',
    value: 0,
    order: 110,
    question: 8,
  },
  {
    sentence: 'Perceptivo',
    value: 0,
    order: 111,
    question: 8,
  },
  {
    sentence: 'Sequencial',
    value: 0,
    order: 112,
    question: 8,
  },
  {
    sentence: 'Teórico',
    value: 0,
    order: 113,
    question: 8,
  },
  {
    sentence: 'Explorador',
    value: 0,
    order: 114,
    question: 8,
  },
  {
    sentence: 'Avaliador',
    value: 0,
    order: 115,
    question: 8,
  },
  {
    sentence: 'Cinestésico',
    value: 0,
    order: 116,
    question: 8,
  },
  {
    sentence: 'Sentimental',
    value: 0,
    order: 117,
    question: 8,
  },
  {
    sentence: 'Preparado',
    value: 0,
    order: 118,
    question: 8,
  },
  {
    sentence: 'Quantitativo',
    value: 0,
    order: 119,
    question: 8,
  },
  {
    sentence: 'Sintético',
    value: 0,
    order: 120,
    question: 8,
  },
  {
    sentence: 'Viciado em números',
    value: 0,
    order: 121,
    question: 9,
  },
  {
    sentence: 'Coração mole',
    value: 0,
    order: 122,
    question: 9,
  },
  {
    sentence: 'Exigente, esforçado',
    value: 0,
    order: 123,
    question: 9,
  },
  {
    sentence: 'Vive no mundo da lua',
    value: 0,
    order: 124,
    question: 9,
  },
  {
    sentence: 'Tem sede de poder',
    value: 0,
    order: 125,
    question: 9,
  },
  {
    sentence: 'Fala demais',
    value: 0,
    order: 126,
    question: 9,
  },
  {
    sentence: 'Não decide sozinho',
    value: 0,
    order: 127,
    question: 9,
  },
  {
    sentence: 'Não sabe se concentrar',
    value: 0,
    order: 128,
    question: 9,
  },
  {
    sentence: 'Frio, insensível',
    value: 0,
    order: 129,
    question: 9,
  },
  {
    sentence: 'Fácil de convencer',
    value: 0,
    order: 130,
    question: 9,
  },
  {
    sentence: 'Sem imaginação',
    value: 0,
    order: 131,
    question: 9,
  },
  {
    sentence: 'Maluco',
    value: 0,
    order: 132,
    question: 9,
  },
  {
    sentence: 'Calculista',
    value: 0,
    order: 133,
    question: 9,
  },
  {
    sentence: 'Ingênuo',
    value: 0,
    order: 134,
    question: 9,
  },
  {
    sentence: 'Bitolado',
    value: 0,
    order: 135,
    question: 9,
  },
  {
    sentence: 'Inconsequente',
    value: 0,
    order: 136,
    question: 9,
  },
  {
    sentence: 'Não se mistura',
    value: 0,
    order: 137,
    question: 9,
  },
  {
    sentence: 'Ultra-sensível',
    value: 0,
    order: 138,
    question: 9,
  },
  {
    sentence: 'Quadrado',
    value: 0,
    order: 139,
    question: 9,
  },
  {
    sentence: 'Sem disciplina',
    value: 0,
    order: 140,
    question: 9,
  },
  {
    sentence: 'Visualizo os "fatos" tratanto-os de forma intuitiva e holística',
    value: 0,
    order: 141,
    question: 10,
  },
  {
    sentence: 'Organizo os "fatos" tratanto os detalhes de forma realista e cronológica',
    value: 0,
    order: 142,
    question: 10,
  },
  {
    sentence: 'Organizo os "fatos" tratanto os detalhes de forma realista e cronológica',
    value: 0,
    order: 143,
    question: 10,
  },
  {
    sentence: 'Analiso os "fatos" tratando-os de forma lógica e racional',
    value: 0,
    order: 144,
    question: 10,
  },
  {
    sentence: 'Uma visão interpessoal, emocional "humana"',
    value: 0,
    order: 145,
    question: 11,
  },
  {
    sentence: 'Uma visão organizada, detalhada, "cronológica"',
    value: 0,
    order: 146,
    question: 11,
  },
  {
    sentence: 'Uma visão analítica, lógica, racional, "de resultados"',
    value: 0,
    order: 147,
    question: 11,
  },
  {
    sentence: 'Uma visão intuitiva, conceitual, visual, de "contexto geral"',
    value: 0,
    order: 148,
    question: 11,
  },
  {
    sentence: 'Sempre fazemos desta forma…',
    value: 0,
    order: 149,
    question: 12,
  },
  {
    sentence: 'Sempre fazemos desta forma…',
    value: 0,
    order: 150,
    question: 12,
  },
  {
    sentence: 'Vejamos os valores humanos…',
    value: 0,
    order: 151,
    question: 12,
  },
  {
    sentence: 'Vamos analisar…',
    value: 0,
    order: 152,
    question: 12,
  },
  {
    sentence: 'Vamos analisar…',
    value: 0,
    order: 153,
    question: 12,
  },
  {
    sentence: 'Vamos ver o desenvolvimento de equipe…',
    value: 0,
    order: 154,
    question: 12,
  },
  {
    sentence: 'Vamos conhecer o resultado…',
    value: 0,
    order: 155,
    question: 12,
  },
  {
    sentence: 'Este é o grande sucesso conceitual…',
    value: 0,
    order: 156,
    question: 12,
  },
  {
    sentence: 'Vamos manter a lei e a ordem…',
    value: 0,
    order: 157,
    question: 12,
  },
  {
    sentence: 'Vamos inovar e criar sinergia…',
    value: 0,
    order: 158,
    question: 12,
  },
  {
    sentence: 'Vamos praticar e envolver…',
    value: 0,
    order: 159,
    question: 12,
  },
  {
    sentence: 'É mais seguro desta forma…',
    value: 0,
    order: 160,
    question: 12,
  },
]
